services:
  db:
    image: postgres:16
    container_name: todo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: canek
      POSTGRES_PASSWORD: Canek123
      POSTGRES_DB: tododb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U canek -d tododb"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: todo-api
    restart: unless-stopped
    ports:
      - "5188:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=tododb;Username=canek;Password=Canek123;SSL Mode=Prefer;Trust Server Certificate=true;
    depends_on:
      db:
        condition: service_healthy
    # ← AQUÍ VA EL COMMAND, FUERA DE depends_on
    command: ["dotnet", "TodoApi.dll", "--migrate"]

volumes:
  postgres_data:
